app_id: "bdd712a8-5515-47bf-b230-ae35e3729bb3"
app_secret: "EA_MHSdPHGy0~GQU0_L-2u-KuMx7RnR159"
redirect: "http://localhost/callback"
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/organizations/"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"